// ─── TrainingReview ───────────────────────────────────────────────────────────
// Post-interview Training Mode panel.
// Displays annotated transcript with per-turn ratings, coaching notes,
// and ideal answers — generated by the backend training agent.
//
// States: loading (fetching/generating), error, loaded (full review)

import { useCallback, useEffect, useState } from "react";
import {
  BookOpen,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  ChevronDown,
  Lightbulb,
  RefreshCw,
  TrendingUp,
} from "lucide-react";
import type { TrainingReview, TrainingTurn, TurnRating } from "@/types/session";
import { api } from "@/services/api";
import { useInView } from "@/hooks/useInView";

// ─── Rating config ────────────────────────────────────────────────────────────

interface RatingConfig {
  icon: React.ReactNode;
  label: string;
  borderClass: string;
  bgClass: string;
  textClass: string;
  dotClass: string;
}

function getRatingConfig(rating: TurnRating): RatingConfig {
  switch (rating) {
    case "strong":
      return {
        icon: <CheckCircle2 className="size-3.5" strokeWidth={2} />,
        label: "Strong",
        borderClass: "border-l-[#1A3D28]",
        bgClass: "bg-[#0A1F12]/30",
        textClass: "text-[#C8FF00]",
        dotClass: "bg-[#C8FF00]",
      };
    case "weak":
      return {
        icon: <AlertTriangle className="size-3.5" strokeWidth={2} />,
        label: "Weak",
        borderClass: "border-l-yellow-700/60",
        bgClass: "bg-yellow-950/10",
        textClass: "text-yellow-400",
        dotClass: "bg-yellow-400",
      };
    case "missed":
      return {
        icon: <XCircle className="size-3.5" strokeWidth={2} />,
        label: "Missed",
        borderClass: "border-l-red-700/60",
        bgClass: "bg-red-950/10",
        textClass: "text-red-400",
        dotClass: "bg-red-400",
      };
  }
}

// ─── Summary bar ──────────────────────────────────────────────────────────────

function ReviewSummary({ review }: { review: TrainingReview }) {
  const turns = review.turns;
  const strong = turns.filter((t) => t.rating === "strong").length;
  const weak = turns.filter((t) => t.rating === "weak").length;
  const missed = turns.filter((t) => t.rating === "missed").length;
  const total = turns.length;

  return (
    <div className="rounded-xl border border-[#1e1e1e] bg-[#0c0c0c] p-5 flex flex-col gap-4">
      {/* Summary text */}
      <div className="flex items-start gap-3">
        <div className="flex-shrink-0 w-6 h-6 rounded-md bg-[#0A1F12] border border-[#1A3D28]/60 flex items-center justify-center mt-0.5">
          <BookOpen className="size-3 text-[#C8FF00]" strokeWidth={1.5} />
        </div>
        <p className="text-sm text-[#a0a0a0] leading-relaxed">{review.overall_summary}</p>
      </div>

      {/* Score bar */}
      {total > 0 && (
        <div className="flex items-center gap-3">
          <div className="flex-1 flex h-2 rounded-full overflow-hidden gap-px">
            {strong > 0 && (
              <div
                className="bg-[#C8FF00]/70 transition-all duration-700"
                style={{ width: `${(strong / total) * 100}%` }}
              />
            )}
            {weak > 0 && (
              <div
                className="bg-yellow-400/60 transition-all duration-700"
                style={{ width: `${(weak / total) * 100}%` }}
              />
            )}
            {missed > 0 && (
              <div
                className="bg-red-400/60 transition-all duration-700"
                style={{ width: `${(missed / total) * 100}%` }}
              />
            )}
          </div>
          <div className="flex items-center gap-3 text-xs font-mono text-[#5a5a5a] flex-shrink-0">
            {strong > 0 && <span className="text-[#C8FF00]/80">{strong} strong</span>}
            {weak > 0 && <span className="text-yellow-400/80">{weak} weak</span>}
            {missed > 0 && <span className="text-red-400/80">{missed} missed</span>}
          </div>
        </div>
      )}

      {/* Top improvements */}
      {review.top_improvements.length > 0 && (
        <div className="border-t border-[#1e1e1e] pt-4 flex flex-col gap-2">
          <p className="text-[10px] font-mono tracking-widest text-[#5a5a5a] uppercase mb-1">
            Key Improvements
          </p>
          <ul className="flex flex-col gap-2">
            {review.top_improvements.map((item, i) => (
              <li key={i} className="flex gap-2 items-start">
                <TrendingUp className="size-3 flex-shrink-0 mt-0.5 text-[#C8FF00]/60" strokeWidth={2} />
                <span className="text-xs text-[#a0a0a0] leading-snug">{item}</span>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}

// ─── Single turn card ─────────────────────────────────────────────────────────

function TurnCard({ turn, index }: { turn: TrainingTurn; index: number }) {
  const [expanded, setExpanded] = useState(false);
  const [ref, inView] = useInView();
  const cfg = getRatingConfig(turn.rating);

  return (
    <div
      ref={ref as React.RefObject<HTMLDivElement>}
      className={`anim-hidden ${inView ? "anim-fade-up" : ""}`}
      style={{ animationDelay: `${index * 40}ms` }}
    >
      <button
        onClick={() => setExpanded((v) => !v)}
        className={`
          w-full text-left rounded-xl border-l-4 border border-[#1e1e1e] bg-[#0c0c0c]
          transition-all duration-200
          ${cfg.borderClass}
          ${expanded ? cfg.bgClass : "hover:bg-[#0f0f0f]"}
        `}
      >
        {/* Header row */}
        <div className="flex items-start gap-3 p-4">
          {/* Rating dot */}
          <div className={`w-2 h-2 rounded-full mt-1.5 flex-shrink-0 ${cfg.dotClass}`} />

          {/* Content */}
          <div className="flex-1 min-w-0">
            {/* Sam's question (if available) */}
            {turn.question && (
              <p className="text-[10px] font-mono text-[#5a5a5a] mb-1 truncate">
                Sam: {turn.question}
              </p>
            )}
            <p className={`text-sm text-[#a0a0a0] leading-snug ${expanded ? "" : "line-clamp-2"}`}>
              {turn.text}
            </p>
          </div>

          {/* Rating badge + expand */}
          <div className="flex items-center gap-2 flex-shrink-0">
            <span className={`flex items-center gap-1 text-[10px] font-mono ${cfg.textClass}`}>
              {cfg.icon}
              {cfg.label}
            </span>
            <ChevronDown
              className={`size-4 text-[#5a5a5a] transition-transform duration-200 ${expanded ? "rotate-180" : ""}`}
              strokeWidth={1.5}
            />
          </div>
        </div>

        {/* Expanded: annotation + ideal answer */}
        <div
          className={`overflow-hidden transition-all duration-300 ease-in-out ${
            expanded ? "max-h-[500px] opacity-100" : "max-h-0 opacity-0"
          }`}
        >
          <div className="px-4 pb-4 pt-1 border-t border-[#1e1e1e] flex flex-col gap-3">
            {/* Annotation */}
            {turn.annotation && (
              <div className="flex gap-2 items-start">
                <div className={`flex-shrink-0 mt-0.5 text-xs font-mono ${cfg.textClass} opacity-70 w-14`}>
                  Note
                </div>
                <p className="text-sm text-[#a0a0a0] leading-relaxed">{turn.annotation}</p>
              </div>
            )}

            {/* Ideal answer */}
            {turn.ideal_answer && (
              <div className="rounded-lg border border-[#1A3D28]/50 bg-[#0A1F12]/40 p-3 flex gap-2 items-start">
                <Lightbulb className="size-3.5 flex-shrink-0 mt-0.5 text-[#C8FF00]/80" strokeWidth={1.5} />
                <div>
                  <p className="text-[10px] font-mono tracking-widest text-[#C8FF00]/60 uppercase mb-1">
                    Ideal answer
                  </p>
                  <p className="text-sm text-[#c0c0c0] leading-relaxed">{turn.ideal_answer}</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </button>
    </div>
  );
}

// ─── Loading state ────────────────────────────────────────────────────────────

function TrainingReviewLoading() {
  return (
    <div className="flex flex-col gap-4 pb-8 animate-[fade-in_0.4s_ease_both]">
      {/* Summary skeleton */}
      <div className="rounded-xl border border-[#1e1e1e] bg-[#0c0c0c] p-5 flex flex-col gap-3">
        <div className="h-3.5 w-48 rounded-md bg-[#1e1e1e] animate-pulse" />
        <div className="h-3 w-full rounded-md bg-[#161616] animate-pulse" />
        <div className="h-3 w-4/5 rounded-md bg-[#161616] animate-pulse" />
        <div className="h-2 w-full rounded-full bg-[#1e1e1e] animate-pulse mt-1" />
      </div>

      {/* Turn skeletons */}
      {[0, 1, 2, 3].map((i) => (
        <div
          key={i}
          className="rounded-xl border border-[#1e1e1e] bg-[#0c0c0c] p-4 flex items-start gap-3"
        >
          <div className="w-2 h-2 rounded-full bg-[#1e1e1e] mt-1.5 animate-pulse flex-shrink-0" />
          <div className="flex-1 flex flex-col gap-2">
            <div className="h-3 w-3/4 rounded-md bg-[#1e1e1e] animate-pulse" />
            <div className="h-3 w-1/2 rounded-md bg-[#161616] animate-pulse" />
          </div>
          <div className="h-4 w-14 rounded-full bg-[#1e1e1e] animate-pulse flex-shrink-0" />
        </div>
      ))}

      <div className="flex items-center justify-center gap-2 py-2">
        <div className="w-3.5 h-3.5 rounded-full border-2 border-[#1e1e1e] border-t-[#C8FF00] animate-spin flex-shrink-0" />
        <p className="text-xs font-mono text-[#5a5a5a]">
          Analyzing your interview… usually 15–30 seconds
        </p>
      </div>
    </div>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────

interface TrainingReviewPanelProps {
  sessionId: string;
}

export default function TrainingReviewPanel({ sessionId }: TrainingReviewPanelProps) {
  const [review, setReview] = useState<TrainingReview | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchReview = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const data = await api.getTrainingReview(sessionId);
      setReview(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load training review.");
    } finally {
      setIsLoading(false);
    }
  }, [sessionId]);

  useEffect(() => {
    fetchReview();
  }, [fetchReview]);

  if (isLoading) return <TrainingReviewLoading />;

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[300px] gap-4 text-center px-6">
        <div className="w-10 h-10 rounded-2xl bg-red-950/40 border border-red-900/30 flex items-center justify-center">
          <XCircle className="size-5 text-red-400" strokeWidth={1.5} />
        </div>
        <div>
          <h3 className="text-sm font-semibold text-[#f0f0f0] mb-1">Couldn't load review</h3>
          <p className="text-xs text-[#5a5a5a] max-w-xs leading-relaxed">{error}</p>
        </div>
        <button
          onClick={fetchReview}
          className="flex items-center gap-2 px-4 py-2 rounded-lg border border-[#2a2a2a] text-sm text-[#a0a0a0] hover:border-[#3a3a3a] hover:text-[#f0f0f0] transition-colors duration-150"
        >
          <RefreshCw className="size-3.5" strokeWidth={1.5} />
          Retry
        </button>
      </div>
    );
  }

  if (!review) return null;

  return (
    <div className="flex flex-col gap-4 pb-8">
      {/* Summary + improvements */}
      <ReviewSummary review={review} />

      {/* Per-turn annotations */}
      {review.turns.length > 0 ? (
        <div className="flex flex-col gap-2">
          <p className="text-[10px] font-mono tracking-widest text-[#5a5a5a] uppercase mb-1">
            Answer-by-Answer
          </p>
          {review.turns.map((turn, i) => (
            <TurnCard key={turn.turn_index} turn={turn} index={i} />
          ))}
        </div>
      ) : (
        <div className="text-center py-8">
          <p className="text-sm text-[#5a5a5a]">No founder turns found in the transcript.</p>
        </div>
      )}
    </div>
  );
}
