// ─── TrainingReview ───────────────────────────────────────────────────────────
// Post-interview Training Mode panel.
// Displays annotated transcript with per-turn ratings, coaching notes,
// and ideal answers — generated by the backend training agent.
//
// States: loading (fetching/generating), error, loaded (full review)
//
// Layout:
//   1. ScoreHeader — donut ring + summary text + score legend
//   2. Top Improvements — key coaching items
//   3. FilterPills — All / Strong / Weak / Missed
//   4. TurnCard list — per-answer accordion with Q&A separation

import { useCallback, useEffect, useState } from "react";
import {
  BookOpen,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  ChevronDown,
  Lightbulb,
  RefreshCw,
  TrendingUp,
  SlidersHorizontal,
  MessageSquare,
} from "lucide-react";
import type { TrainingReview, TrainingTurn, TurnRating } from "@/types/session";
import { api } from "@/services/api";
import { useInView } from "@/hooks/useInView";

// ─── Rating config ────────────────────────────────────────────────────────────

interface RatingConfig {
  icon: React.ReactNode;
  label: string;
  borderAccent: string;
  bgClass: string;
  textClass: string;
  dotClass: string;
  expandedBorder: string;
  pillActive: string;
}

function getRatingConfig(rating: TurnRating): RatingConfig {
  switch (rating) {
    case "strong":
      return {
        icon: <CheckCircle2 className="size-3.5" strokeWidth={2} />,
        label: "Strong",
        borderAccent: "border-l-[#C8FF00]/50",
        bgClass: "bg-[#0A1F12]/20",
        textClass: "text-[#C8FF00]",
        dotClass: "bg-[#C8FF00]",
        expandedBorder: "border-[#1A3D28]/60",
        pillActive: "bg-[#0A1F12] border-[#C8FF00]/40 text-[#C8FF00]",
      };
    case "weak":
      return {
        icon: <AlertTriangle className="size-3.5" strokeWidth={2} />,
        label: "Weak",
        borderAccent: "border-l-amber-500/50",
        bgClass: "bg-amber-950/10",
        textClass: "text-amber-400",
        dotClass: "bg-amber-400",
        expandedBorder: "border-amber-900/30",
        pillActive: "bg-amber-950/30 border-amber-700/40 text-amber-400",
      };
    case "missed":
      return {
        icon: <XCircle className="size-3.5" strokeWidth={2} />,
        label: "Missed",
        borderAccent: "border-l-red-500/50",
        bgClass: "bg-red-950/10",
        textClass: "text-red-400",
        dotClass: "bg-red-400",
        expandedBorder: "border-red-900/30",
        pillActive: "bg-red-950/30 border-red-700/40 text-red-400",
      };
  }
}

// ─── Filter type ──────────────────────────────────────────────────────────────

type FilterValue = "all" | TurnRating;

// ─── Score donut ring (SVG) ───────────────────────────────────────────────────

function ScoreDonut({
  strong,
  weak,
  missed,
  total,
}: {
  strong: number;
  weak: number;
  missed: number;
  total: number;
}) {
  const size = 88;
  const r = 36;
  const cx = size / 2;
  const cy = size / 2;
  const circumference = 2 * Math.PI * r;
  const gap = 2; // px gap between segments

  // Build segments
  const segments = [
    { count: strong, color: "#C8FF00", opacity: 0.85 },
    { count: weak, color: "#F59E0B", opacity: 0.85 },
    { count: missed, color: "#EF4444", opacity: 0.85 },
  ].filter((s) => s.count > 0);

  const score = total > 0 ? Math.round((strong / total) * 100) : 0;

  let offset = -circumference / 4; // start at 12 o'clock
  const arcs = segments.map((seg) => {
    const segLen = (seg.count / total) * circumference - gap;
    const arc = { ...seg, dasharray: `${segLen} ${circumference - segLen}`, offset };
    offset += (seg.count / total) * circumference;
    return arc;
  });

  return (
    <div className="relative flex-shrink-0" style={{ width: size, height: size }}>
      <svg width={size} height={size} className="-rotate-0">
        {/* Track */}
        <circle
          cx={cx} cy={cy} r={r}
          fill="none"
          stroke="#1e1e1e"
          strokeWidth={8}
        />
        {/* Segments */}
        {arcs.map((arc, i) => (
          <circle
            key={i}
            cx={cx} cy={cy} r={r}
            fill="none"
            stroke={arc.color}
            strokeOpacity={arc.opacity}
            strokeWidth={8}
            strokeLinecap="butt"
            strokeDasharray={arc.dasharray}
            strokeDashoffset={-arc.offset}
            style={{ transition: "stroke-dasharray 0.7s ease" }}
          />
        ))}
      </svg>
      {/* Center score */}
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <span className="text-xl font-bold font-mono text-[#f0f0f0] leading-none">{score}</span>
        <span className="text-[9px] font-mono text-[#5a5a5a] uppercase tracking-widest leading-none mt-0.5">score</span>
      </div>
    </div>
  );
}

// ─── Score header ─────────────────────────────────────────────────────────────

function ScoreHeader({ review }: { review: TrainingReview }) {
  const turns = review.turns;
  const strong = turns.filter((t) => t.rating === "strong").length;
  const weak = turns.filter((t) => t.rating === "weak").length;
  const missed = turns.filter((t) => t.rating === "missed").length;
  const total = turns.length;

  const legend = [
    { label: "Strong", count: strong, color: "bg-[#C8FF00]", text: "text-[#C8FF00]" },
    { label: "Weak", count: weak, color: "bg-amber-400", text: "text-amber-400" },
    { label: "Missed", count: missed, color: "bg-red-400", text: "text-red-400" },
  ];

  return (
    <div className="rounded-xl border border-[#1A3D28]/40 bg-[#0A1F12]/20 p-5 flex gap-5 items-start">
      {/* Donut */}
      <ScoreDonut strong={strong} weak={weak} missed={missed} total={total} />

      {/* Right side */}
      <div className="flex-1 min-w-0 flex flex-col gap-3">
        {/* Title row */}
        <div className="flex items-center gap-2">
          <div className="flex items-center justify-center w-6 h-6 rounded-md bg-[#0A1F12] border border-[#1A3D28]/60 flex-shrink-0">
            <BookOpen className="size-3 text-[#C8FF00]" strokeWidth={1.5} />
          </div>
          <p className="text-[10px] font-mono tracking-widest text-[#5a5a5a] uppercase">
            Training Review
          </p>
        </div>

        {/* Summary text */}
        <p className="text-sm text-[#a0a0a0] leading-relaxed">{review.overall_summary}</p>

        {/* Legend pills */}
        <div className="flex items-center gap-3">
          {legend.map(({ label, count, color, text }) =>
            count > 0 ? (
              <div key={label} className="flex items-center gap-1.5">
                <span className={`w-2 h-2 rounded-full flex-shrink-0 ${color}`} />
                <span className={`text-xs font-mono font-semibold ${text}`}>{count}</span>
                <span className="text-xs font-mono text-[#5a5a5a]">{label.toLowerCase()}</span>
              </div>
            ) : null
          )}
        </div>

        {/* Segmented progress bar */}
        {total > 0 && (
          <div className="flex h-1 rounded-full overflow-hidden gap-px">
            {strong > 0 && (
              <div className="bg-[#C8FF00]/70 transition-all duration-700" style={{ width: `${(strong / total) * 100}%` }} />
            )}
            {weak > 0 && (
              <div className="bg-amber-400/60 transition-all duration-700" style={{ width: `${(weak / total) * 100}%` }} />
            )}
            {missed > 0 && (
              <div className="bg-red-400/60 transition-all duration-700" style={{ width: `${(missed / total) * 100}%` }} />
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// ─── Top improvements ─────────────────────────────────────────────────────────

function TopImprovements({ items }: { items: string[] }) {
  if (items.length === 0) return null;

  return (
    <div className="rounded-xl border border-amber-900/25 bg-amber-950/8 p-4 flex flex-col gap-3">
      <div className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <div className="flex items-center justify-center w-6 h-6 rounded-md bg-[#1a1400]/60 border border-yellow-900/30 flex-shrink-0">
            <TrendingUp className="size-3 text-amber-400" strokeWidth={1.5} />
          </div>
          <p className="text-[10px] font-mono tracking-widest text-[#5a5a5a] uppercase">
            Key Improvements
          </p>
        </div>
        <span className="text-[9px] font-mono text-[#3a3a3a]">{items.length} items</span>
      </div>
      {/* Scrollable list capped at ~4 items visible */}
      <div className="relative">
        <ul className="flex flex-col gap-2 max-h-[200px] overflow-y-auto pr-1 scrollbar-thin">
          {items.map((item, i) => (
            <li key={i} className="flex gap-2.5 items-start">
              <span className="flex-shrink-0 w-4 h-4 rounded-full bg-amber-950/40 border border-amber-900/30 text-[9px] font-mono text-amber-400/80 flex items-center justify-center mt-0.5">
                {i + 1}
              </span>
              <span className="text-sm text-[#a0a0a0] leading-snug">{item}</span>
            </li>
          ))}
        </ul>
        {/* Fade hint at the bottom when list is scrollable */}
        {items.length > 4 && (
          <div className="pointer-events-none absolute bottom-0 left-0 right-0 h-8 bg-gradient-to-t from-amber-950/20 to-transparent rounded-b-lg" />
        )}
      </div>
    </div>
  );
}

// ─── Filter pills ─────────────────────────────────────────────────────────────

function FilterPills({
  active,
  counts,
  onChange,
}: {
  active: FilterValue;
  counts: { strong: number; weak: number; missed: number; total: number };
  onChange: (v: FilterValue) => void;
}) {
  const pills: { value: FilterValue; label: string; count: number; activeClass: string }[] = [
    {
      value: "all",
      label: "All",
      count: counts.total,
      activeClass: "bg-[#1e1e1e] border-[#3a3a3a] text-[#f0f0f0]",
    },
    {
      value: "strong",
      label: "Strong",
      count: counts.strong,
      activeClass: "bg-[#0A1F12] border-[#C8FF00]/40 text-[#C8FF00]",
    },
    {
      value: "weak",
      label: "Weak",
      count: counts.weak,
      activeClass: "bg-amber-950/30 border-amber-700/40 text-amber-400",
    },
    {
      value: "missed",
      label: "Missed",
      count: counts.missed,
      activeClass: "bg-red-950/30 border-red-700/40 text-red-400",
    },
  ];

  return (
    <div className="flex items-center gap-1.5 flex-shrink-0">
      <SlidersHorizontal className="size-3 text-[#3a3a3a] flex-shrink-0" strokeWidth={1.5} />
      {pills.map(({ value, label, count, activeClass }) => (
        <button
          key={value}
          onClick={() => onChange(value)}
          className={`
            flex items-center gap-1 px-2.5 py-1 rounded-full border text-[10px] font-mono transition-all duration-150
            ${active === value
              ? activeClass
              : "border-[#1e1e1e] text-[#3a3a3a] hover:border-[#2a2a2a] hover:text-[#5a5a5a]"}
          `}
        >
          {label}
          <span className={`${active === value ? "opacity-60" : "opacity-40"}`}>{count}</span>
        </button>
      ))}
    </div>
  );
}

// ─── Single turn card ─────────────────────────────────────────────────────────

function TurnCard({ turn, index }: { turn: TrainingTurn; index: number }) {
  const [expanded, setExpanded] = useState(false);
  const [ref, inView] = useInView();
  const cfg = getRatingConfig(turn.rating);

  return (
    <div
      ref={ref as React.RefObject<HTMLDivElement>}
      className={`anim-hidden ${inView ? "anim-fade-up" : ""}`}
      style={{ animationDelay: `${Math.min(index * 40, 400)}ms` }}
    >
      <div
        className={`
          rounded-xl border-l-4 border border-[#1e1e1e]
          transition-colors duration-200
          ${cfg.borderAccent}
          ${expanded ? cfg.bgClass : "bg-[#0c0c0c]"}
        `}
      >
        {/* Collapsed header — always visible */}
        <button
          onClick={() => setExpanded((v) => !v)}
          className="w-full text-left p-4 flex flex-col gap-2.5"
        >
          {/* Sam's question */}
          {turn.question && (
            <div className="flex items-start gap-2">
              <div className="flex items-center justify-center w-4 h-4 rounded bg-[#161616] border border-[#1e1e1e] flex-shrink-0 mt-0.5">
                <MessageSquare className="size-2.5 text-[#5a5a5a]" strokeWidth={2} />
              </div>
              <p className="text-[11px] font-mono text-[#5a5a5a] leading-snug italic">
                {turn.question}
              </p>
            </div>
          )}

          {/* Your answer + rating + chevron */}
          <div className="flex items-start gap-3">
            <div className={`w-2 h-2 rounded-full mt-1.5 flex-shrink-0 ${cfg.dotClass}`} />
            <p className={`flex-1 text-sm text-[#c0c0c0] leading-snug ${expanded ? "" : "line-clamp-2"}`}>
              {turn.text}
            </p>
            <div className="flex items-center gap-1.5 flex-shrink-0">
              <span className={`flex items-center gap-1 text-[10px] font-mono font-semibold ${cfg.textClass}`}>
                {cfg.icon}
                {cfg.label}
              </span>
              <ChevronDown
                className={`size-4 text-[#5a5a5a] transition-transform duration-200 ${expanded ? "rotate-180" : ""}`}
                strokeWidth={1.5}
              />
            </div>
          </div>
        </button>

        {/* Expanded body */}
        <div
          className={`overflow-hidden transition-all duration-300 ease-in-out ${
            expanded ? "max-h-[600px] opacity-100" : "max-h-0 opacity-0"
          }`}
        >
          <div className={`mx-4 mb-4 rounded-lg border ${cfg.expandedBorder} overflow-hidden`}>
            {/* Coaching note */}
            {turn.annotation && (
              <div className="px-4 py-3 flex gap-3 items-start border-b border-[#1e1e1e]">
                <AlertTriangle className={`size-3.5 flex-shrink-0 mt-0.5 ${cfg.textClass} opacity-70`} strokeWidth={2} />
                <div>
                  <p className={`text-[10px] font-mono tracking-widest uppercase mb-1 ${cfg.textClass} opacity-60`}>
                    Coaching Note
                  </p>
                  <p className="text-sm text-[#a0a0a0] leading-relaxed">{turn.annotation}</p>
                </div>
              </div>
            )}

            {/* Ideal answer */}
            {turn.ideal_answer && (
              <div className="px-4 py-3 flex gap-3 items-start bg-[#0A1F12]/30">
                <Lightbulb className="size-3.5 flex-shrink-0 mt-0.5 text-[#C8FF00]/80" strokeWidth={1.5} />
                <div>
                  <p className="text-[10px] font-mono tracking-widest text-[#C8FF00]/60 uppercase mb-1">
                    Ideal Answer
                  </p>
                  <p className="text-sm text-[#c8c8c8] leading-relaxed">{turn.ideal_answer}</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

// ─── Loading state ────────────────────────────────────────────────────────────

function TrainingReviewLoading() {
  return (
    <div className="flex flex-col gap-4 pb-8 animate-[fade-in_0.4s_ease_both]">
      {/* Header skeleton */}
      <div className="rounded-xl border border-[#1e1e1e] bg-[#0c0c0c] p-5 flex gap-5 items-start">
        {/* Donut placeholder */}
        <div className="w-[88px] h-[88px] rounded-full border-[8px] border-[#1e1e1e] flex-shrink-0 animate-pulse" />
        <div className="flex-1 flex flex-col gap-3 pt-1">
          <div className="h-3 w-24 rounded-md bg-[#1e1e1e] animate-pulse" />
          <div className="h-3 w-full rounded-md bg-[#161616] animate-pulse" />
          <div className="h-3 w-4/5 rounded-md bg-[#161616] animate-pulse" />
          <div className="flex gap-3">
            {[0, 1, 2].map((i) => (
              <div key={i} className="h-3 w-16 rounded-full bg-[#1e1e1e] animate-pulse" />
            ))}
          </div>
        </div>
      </div>

      {/* Turn skeletons */}
      {[0, 1, 2, 3].map((i) => (
        <div
          key={i}
          className="rounded-xl border border-[#1e1e1e] bg-[#0c0c0c] p-4 flex flex-col gap-2.5"
        >
          <div className="h-2.5 w-3/4 rounded-md bg-[#161616] animate-pulse" />
          <div className="flex items-start gap-3">
            <div className="w-2 h-2 rounded-full bg-[#1e1e1e] mt-1.5 animate-pulse flex-shrink-0" />
            <div className="flex-1 flex flex-col gap-2">
              <div className="h-3.5 w-full rounded-md bg-[#1e1e1e] animate-pulse" />
              <div className="h-3.5 w-3/5 rounded-md bg-[#161616] animate-pulse" />
            </div>
            <div className="h-4 w-14 rounded-full bg-[#1e1e1e] animate-pulse flex-shrink-0" />
          </div>
        </div>
      ))}

      <div className="flex items-center justify-center gap-2 py-2">
        <div className="w-3.5 h-3.5 rounded-full border-2 border-[#1e1e1e] border-t-[#C8FF00] animate-spin flex-shrink-0" />
        <p className="text-xs font-mono text-[#5a5a5a]">
          Analyzing your interview… usually 15–30 seconds
        </p>
      </div>
    </div>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────

interface TrainingReviewPanelProps {
  sessionId: string;
}

export default function TrainingReviewPanel({ sessionId }: TrainingReviewPanelProps) {
  const [review, setReview] = useState<TrainingReview | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [filter, setFilter] = useState<FilterValue>("all");

  const fetchReview = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const data = await api.getTrainingReview(sessionId);
      setReview(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load training review.");
    } finally {
      setIsLoading(false);
    }
  }, [sessionId]);

  useEffect(() => {
    fetchReview();
  }, [fetchReview]);

  if (isLoading) return <TrainingReviewLoading />;

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[300px] gap-4 text-center px-6">
        <div className="w-10 h-10 rounded-2xl bg-red-950/40 border border-red-900/30 flex items-center justify-center">
          <XCircle className="size-5 text-red-400" strokeWidth={1.5} />
        </div>
        <div>
          <h3 className="text-sm font-semibold text-[#f0f0f0] mb-1">Couldn't load review</h3>
          <p className="text-xs text-[#5a5a5a] max-w-xs leading-relaxed">{error}</p>
        </div>
        <button
          onClick={fetchReview}
          className="flex items-center gap-2 px-4 py-2 rounded-lg border border-[#2a2a2a] text-sm text-[#a0a0a0] hover:border-[#3a3a3a] hover:text-[#f0f0f0] transition-colors duration-150"
        >
          <RefreshCw className="size-3.5" strokeWidth={1.5} />
          Retry
        </button>
      </div>
    );
  }

  if (!review) return null;

  const counts = {
    strong: review.turns.filter((t) => t.rating === "strong").length,
    weak: review.turns.filter((t) => t.rating === "weak").length,
    missed: review.turns.filter((t) => t.rating === "missed").length,
    total: review.turns.length,
  };

  const filteredTurns =
    filter === "all" ? review.turns : review.turns.filter((t) => t.rating === filter);

  return (
    <div className="flex flex-col gap-4 pb-8">
      {/* Sticky score header */}
      <div className="sticky top-0 z-10 bg-[#050505]/95 backdrop-blur-sm pt-1 pb-2 -mx-1 px-1">
        <ScoreHeader review={review} />
      </div>

      {/* Top improvements */}
      <TopImprovements items={review.top_improvements} />

      {/* Filter pills + turn list */}
      {review.turns.length > 0 ? (
        <div className="flex flex-col gap-3">
          {/* Pills row */}
          <div className="flex items-center justify-between">
            <p className="text-[10px] font-mono tracking-widest text-[#5a5a5a] uppercase">
              Answer-by-Answer
            </p>
            <FilterPills active={filter} counts={counts} onChange={setFilter} />
          </div>

          {/* Turn cards */}
          <div className="flex flex-col gap-2">
            {filteredTurns.length > 0 ? (
              filteredTurns.map((turn, i) => (
                <TurnCard key={turn.turn_index} turn={turn} index={i} />
              ))
            ) : (
              <div className="rounded-xl border border-[#1e1e1e] bg-[#0c0c0c] p-8 text-center">
                <p className="text-sm text-[#5a5a5a]">No {filter} answers in this session.</p>
              </div>
            )}
          </div>
        </div>
      ) : (
        <div className="rounded-xl border border-[#1e1e1e] bg-[#0c0c0c] p-8 text-center">
          <p className="text-sm text-[#5a5a5a]">No founder turns found in the transcript.</p>
        </div>
      )}
    </div>
  );
}
